#! /bin/bash
#
# Copyright 2018 Undo Ltd.
#
# https://github.com/barisione/clang-format-hooks

# Force variable declaration before access.
set -u

if [ -t 1 ] && which tput > /dev/null 2>&1; then
    readonly b=$(tput bold)
    readonly i=$(tput sitm)
    readonly n=$(tput sgr0)
else
    readonly b=
    readonly i=
    readonly n=
fi

function error_exit() {
    for str in "$@"; do
        echo -n "$b$str$n" >&2
    done
    echo >&2

    exit 1
}

# Find the top-level git directory (taking into account we could be in a submodule).
declare git_test_dir=.
declare top_dir
while true; do
    top_dir=$(cd "$git_test_dir"; git rev-parse --show-toplevel) || \
        error_exit "You need to be in the git repository to run this script."

    [ -e "$top_dir/.git" ] || \
        error_exit "No .git directory in $top_dir."

    if [ -d "$top_dir/.git" ]; then
        # We are done! top_dir is the root git directory.
        break
    else
        # We are in a submodule if .git is a file!
        git_test_dir="$git_test_dir/.."
    fi
done

readonly top_dir

readonly hook_path="$top_dir/.git/hooks/pre-commit"
readonly me=$(realpath "$0")
readonly me_relative_to_hook=$(realpath --relative-to="$(dirname "$hook_path")" "$me")
readonly my_dir=$(dirname "$me")
readonly apply_format="$my_dir/apply-format"
readonly apply_format_relative_to_top_dir=$(realpath --relative-to="$top_dir" "$apply_format")

function is_installed() {
    if [ ! -e "$hook_path" ]; then
        echo nothing
    else
        if [[ "$OSTYPE" =~ darwin.* ]]; then
            # macOS's readlink doesn't have -m, if greadlink is installed we use it.
            readlink=greadlink
            if ! which "$readlink" > /dev/null 2>&1; then
                # Assume it's the same.
                echo installed
                return
            fi
        else
            readlink=readlink
        fi
        readonly existing_hook_target=$("$readlink" -m -- "$hook_path")
        if [ "$existing_hook_target" = "$me" ]; then
            # Already installed.
            echo installed
        else
            # There's a hook, but it's not us.
            echo different
        fi
    fi
}

function install() {
    if ln -s "$me_relative_to_hook" "$hook_path" 2> /dev/null; then
        echo "Pre-commit hook installed."
    else
        local -r res=$(is_installed)
        if [ "$res" = installed ]; then
            error_exit "The hook is already installed."
        elif [ "$res" = different ]; then
            error_exit "There's already an existing pre-commit hook, but for something else."
        elif [ "$res" = nothing ]; then
            error_exit "There's no pre-commit hook, but we couldn't create a symlink."
        else
            error_exit "Unexpected failure."
        fi
    fi
}

function uninstall() {
    local -r res=$(is_installed)
    if [ "$res" = installed ]; then
        rm "$hook_path" || \
            error_exit "Couldn't remove the pre-commit hook."
    elif [ "$res" = different ]; then
        error_exit "There's a pre-commit hook installed, but for something else. Not removing."
    elif [ "$res" = nothing ]; then
        error_exit "There's no pre-commit hook, nothing to uninstall."
    else
        error_exit "Unexpected failure detecting the pre-commit hook status."
    fi
}

function show_help() {
    cat << EOF
${b}SYNOPSIS${n}

    $0 [install|uninstall]

${b}DESCRIPTION${n}

    Git hook to verify and fix formatting before committing.

    The script is invoked automatically when you commit, so you need to call it
    directly only to set up the hook or remove it.

    To setup the hook run this script passing "install" on the command line.
    To remove the hook run passing "uninstall".

${b}CONFIGURATION${n}

    You can configure the hook using the "git config" command.

    ${b}hooks.clangFormatDiffInteractive${n} (default: true)
        By default, the hook requires user input. If you don't run git from a
        terminal, you can disable the interactive prompt with:
            ${i}\$ git config hooks.clangFormatDiffInteractive false${n}

    ${b}hooks.clangFormatDiffStyle${n} (default: file)
        Unless a different style is specified, the hook expects a file named
        .clang-format to exist in the repository. This file should contain the
        configuration for clang-format.
        You can specify a different style (in this example, the WebKit one)
        with:
            ${i}\$ git config hooks.clangFormatDiffStyle WebKit${n}
EOF
}

if [ $# = 1 ]; then
    case "$1" in
        -h | -\? | --help )
            show_help
            exit 0
            ;;
        install )
            install
            exit 0
            ;;
        uninstall )
            uninstall
            exit 0
            ;;
    esac
fi

[ $# = 0 ] || error_exit "Invalid arguments: $*"


# This is a real run of the hook, not a install/uninstall run.

if [ -z "${GIT_DIR:-}" ] && [ -z "${GIT_INDEX_FILE:-}" ]; then
    error_exit \
        $'It looks like you invoked this script directly, but it\'s supposed to be used\n' \
        $'as a pre-commit git hook.\n' \
        $'\n' \
        $'To install the hook try:\n' \
        $'    ' "$0" $' install\n' \
        $'\n' \
        $'For more details on this script try:\n' \
        $'    ' "$0" $' --help\n'
fi

[ -x "$apply_format" ] || \
    error_exit \
    $'Cannot find the apply-format script.\n' \
    $'I expected it here:\n' \
    $'    ' "$apply_format"

readonly style=$(cd "$top_dir" && git config hooks.clangFormatDiffStyle || echo file)

readonly patch=$(mktemp)
trap '{ rm -f "$patch"; }' EXIT
"$apply_format" --style="$style" --cached > "$patch" || \
    error_exit $'\nThe apply-format script failed.'

if [ "$(wc -l < "$patch")" -eq 0 ]; then
    echo "The staged content is formatted correctly."
    exit 0
fi


# The code is not formatted correctly.

interactive=$(cd "$top_dir" && git config --bool hooks.clangFormatDiffInteractive)
if [ "$interactive" != false ]; then
    # Interactive is the default, so anything that is not false is converted to
    # true, including possibly invalid values.
    interactive=true
fi
readonly interactive

if [ "$interactive" = false ]; then
    echo "${b}The staged content is not formatted correctly.${n}"
    echo "You can fix the formatting with:"
    echo "    ${i}\$ ./$apply_format_relative_to_top_dir --apply-to-staged${n}"
    echo
    echo "You can also make this script interactive (if you use git from a terminal) with:"
    echo "    ${i}\$ git config hooks.clangFormatDiffInteractive true${n}"
    exit 1
fi

if which colordiff > /dev/null 2>&1; then
    colordiff < "$patch"
else
    echo "${b}(Install colordiff to see this diff in color!)${n}"
    echo
    cat "$patch"
fi

echo
echo "${b}The staged content is not formatted correctly.${n}"
echo "The patch shown above can be applied automatically to fix the formatting."
echo

echo "You can:"
echo " [a]: Apply the patch"
echo " [f]: Force and commit anyway (not recommended!)"
echo " [c]: Cancel the commit"
echo " [?]: Show help"
echo

readonly tty=${PRE_COMMIT_HOOK_TTY:-/dev/tty}

while true; do
    echo -n "What would you like to do? [a/f/c/?] "
    read -r answer < "$tty"
    case "$answer" in

        [aA] )
            patch -p0 < "$patch" || \
                error_exit \
                $'\n' \
                $'Cannot apply patch to local files.\n' \
                $'Have you modified the file locally after starting the commit?'
            git apply -p0 --cached < "$patch" || \
                error_exit \
                $'\n' \
                $'Cannot apply patch to git staged changes.\n' \
                $'This may happen if you have some overlapping unstaged changes. To solve\n' \
                $'you need to stage or reset changes manually.'
            ;;

        [fF] )
            echo
            echo "Will commit anyway!"
            echo "You can always abort by quitting your editor with no commit message."
            echo
            echo -n "Press return to continue."
            read -r < "$tty"
            exit 0
            ;;

        [cC] )
            error_exit "Commit aborted as requested."
            ;;

        \? )
            echo
            show_help
            echo
            continue
            ;;

        * )
            echo 'Invalid answer. Type "a", "f" or "c".'
            echo
            continue

    esac
    break
done
