#! /bin/bash

# Fail if any test fails.
set -e

echo "== RUNNING TESTS =="
./tests/run.py
echo

echo "== RUNNING PYLINT =="
./tests/run-pylint
echo

echo "== RUNNING SHELLCHECK =="
shellcheck apply-format git-pre-commit-format run-checks
echo
